config/routes.rb
Rails.application.routes.draw do

  root "blogs#index"

  resources :blogs, only:[:index] do
    collection do
      post 'upload_img'
      get 'set'
      post 'set_userinfo'
      get 'set_blog'
      post 'update_blog'
      get 'about'
      get 'change_password'
      post 'update_password'
      post 'preview'
    end

  end

  resources :articles do
    member do
      post 'star'
    end

    resources :comments
  end

  get 'register' => 'users#register'
  get 'login' => 'users#login'
  get 'logout' => 'users#logout'
  resources :users do
    collection do
      get 'register'
      post 'register_confirm'
      get 'login'
      post 'login_confirm'
      get 'logout'
      get 'send_active_mail'
      get 'activation'
      get 'forget_password'
      post 'forget_password_confirm'
      get 'change_pw'
      post 'change_pw_confirm'
    end
  end

end

app/models/user.rb
#encoding: utf-8
class User < ActiveRecord::Base
  has_secure_password

  has_many :articles
  has_many :comments, class_name: 'ArticleComment'

  before_save :set_admin
  validates :username, length: {minimum: 5, maximum: 20}, uniqueness: true
  validates :email, format: {with: /\A[a-zA-Z0-9\-]+@[a-zA-Z0-9-]+\.(org|com|cn|io|net|cc|me)\z/}, uniqueness: true
  validates :password, length: {minimum: 6}, confirmation: true, if: :need_valid_password?
  validates :nick_name, length: {minimum: 2, maximum: 20}, uniqueness: true, if: 'nick_name.present?'

  def nickname
    self.nick_name || self.username
  end

  def set_admin
    self.admin = 0 unless self.admin.present?
  end

  def check_password(password)
    self.authenticate(password)
  end

  def update_last_reply_time
    self.update_attribute last_reply_time: DateTime.now
  end

  def can_reply?
    (DateTime.now.to_i - self.last_reply_time.to_i) > 60
  end

  def need_valid_password?
    new_record? || password.present?
  end
end

app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < ApplicationController
  def register
    @user = User.new
    render 'register', layout: 'register'
  end

  def register_confirm
    @user = User.new params.require(:user).permit(:username,:email,:password,:password_confirmation)
    if @user.save
      #to_login @user
      session[:wait_active_email] = @user.email
      redirect_to send_active_mail_users_path
    else
      render 'register', layout: 'register'
    end
  end

  def login
    return redirect_to(login_path(from: referer)) unless params[:from].present?
    @user = User.new
    render 'login', layout: 'register'
  end

  def login_confirm
    @user = User.find_by username: params[:user][:username]
    unless @user.activation?
      session[:wait_active_email] = @user.email
      flash.now[:error] = "用户还没有激活，<a href='#{send_active_mail_users_path}'>点此</a>发送激活邮件。"
      return render 'login', layout: 'register'
    end
    if @user && @user.check_password(params[:user][:password])
      to_login @user
      @user.update_attribute :last_login_time, DateTime.now
      redirect_to (params[:from].present? ? params[:from] : root_path)
    else
      flash[:error] = '用户名或密码错误'
      render 'login', layout: 'register'
    end
  rescue
    flash[:error] = '用户名或密码错误'
    render 'login', layout: 'register'
  end

  def logout
    session[:user_id] = nil
    redirect_to referer
  end

  def send_active_mail
    @result = {status: false, message: ''}
    if session[:wait_active_email]
      wait_user = User.find_by email: session[:wait_active_email]
      if wait_user.activation?
        flash[:success] = '您的账号已经激活，请登录'
        return redirect_to login_path
      end
      if wait_user.present?
        token = UserActive.generate_token
        active = UserActive.new user_id: wait_user.id, type_name: 'Active', token: token
        url = File.join(Settings.blog.domain, "users/activation?token=#{token}")
        if active.save && UserMailer.auth_mail(session[:wait_active_email], url).deliver
          @result[:status] = true
          @result[:message] = session[:wait_active_email]
        end
      end
    end
  end

  def activation
    active = UserActive.where(type_name: 'Active', token: params[:token], used: 0).order('created_at desc').first
    if active && !active.used?
      user = User.find active.user_id
      user.activation = 1
      active.used = 1
      if user.save && active.save
        flash[:success] = '激活成功，请登录'
        redirect_to login_path
      else
        flash[:error] = '激活失败，请重试，如果还不能激活，请联系管理员'
        redirect_to login_path
      end
    else
      flash[:error] = 'token不存在'
      redirect_to root_path
    end
  end

  def forget_password
    render 'forget_password', layout: 'register'
  end

  def forget_password_confirm
    @result = {status: false, message: ''}
    if params[:user][:email].present?
      user = User.find_by email: params[:user][:email]
      return redirect_to(root_path) unless user
      token = UserActive.generate_token
      active = UserActive.new user_id: user.id, token: token, type_name: 'ForgetPassword'
      url = File.join(Settings.blog.domain, "users/change_pw?token=#{token}")
      if active.save && UserMailer.forget_password(user.email, url).deliver
        @result[:status] = true
        @result[:message] = user.email
      else
        flash.now[:error] = '邮件发送失败，请重试'
        render 'forget_password', layout: 'register'
      end
    end
  end

  def change_pw
    @token = params[:token]
    active = UserActive.where(type_name: 'ForgetPassword', token: @token, used: 0).order('created_at desc').first
    return redirect_to(root_path) unless active
    if Time.now.to_i - active.created_at.to_i > 600
      return redirect_to root_path
    end
    render 'change_pw', layout: 'register'
  end

  def change_pw_confirm
    @token = params[:user][:token]
    active = UserActive.where(type_name: 'ForgetPassword', token: @token, used: 0).order('created_at desc').first
    return redirect_to(root_path) unless active
    @user = User.find active.user_id
    return redirect_to(root_path) unless @user
    @user.password = params[:user][:password] || ''
    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.save
      flash[:success] = '重置密码成功，请登录'
      redirect_to login_path
    else
      flash.now[:error] = @user.errors.full_messages.first
      render 'change_pw', layout: 'register'
    end
  end

  protected

  def to_login(user)
    session[:user_id] = user.id
  end
end

app/views/users/_form.html.haml
- method = action == 'update' ? 'put' : 'post'
- submit_url = case action; when 'register'; register_confirm_users_path; when 'login'; login_confirm_users_path; when 'update'; user_path(@user); end
= form_for @user, method: method, url: submit_url, role: 'form' do |f|
  .form-field.form-group
    = f.text_field :username, placeholder: '用户名', class: 'form-control username', required: true
  .form-field.form-group
    = f.text_field :email, placeholder: '邮箱', class: 'form-control email', required: true
  .form-field.form-group
    = f.password_field :password, placeholder: '密码，最少6位', class: 'form-control password', required: true
  .form-field.form-group
    = f.password_field :password_confirmation, placeholder: '确认密码', class: 'form-control password', required: true
  = submit_tag '注册', class: 'btn btn-primary btn-lg'
  .action-wrapper
    = link_to '已有账号？', login_path

app/views/users/change_pw.html.haml
%section.content
  .form-unit
    = link_to root_path, class: 'brand' do
      %h1= blog_title
    %h3 重置密码
    - if flash[:success].present?
      .alert.alert-success
        %a.close{"data-dismiss"=>"success"} &times;
        %span
          = flash[:success]
    - elsif flash[:error].present?
      .alert.alert-danger
        %a.close{"data-dismiss"=>"alert"} &times;
        %span= raw flash[:error]
    = form_for :user, url: change_pw_confirm_users_path, role: 'form' do |f|
      .form-field.form-group
        = f.hidden_field :token, value: @token
        = f.password_field :password, placeholder: '密码', class: 'form-control', required: true
      .form-field.form-group
        = f.password_field :password_confirmation, placeholder: '确认密码', class: 'form-control password', required: true
      = submit_tag '重置', class: 'btn btn-primary btn-lg'

app/views/users/forget_password.html.haml
%section.content
  .form-unit
    = link_to root_path, class: 'brand' do
      %h1= blog_title
    %h3 找回密码
    - if flash[:success].present?
      .alert.alert-success
        %a.close{"data-dismiss"=>"success"} &times;
        %span
          = flash[:success]
    - elsif flash[:error].present?
      .alert.alert-danger
        %a.close{"data-dismiss"=>"alert"} &times;
        %span= raw flash[:error]
    = form_for :user, url: forget_password_confirm_users_path, role: 'form' do |f|
      .form-field.form-group
        = f.text_field :email, placeholder: '注册邮箱', class: 'form-control', required: true
      = submit_tag '确定', class: 'btn btn-primary btn-lg'

app/views/users/forget_password_confirm.html.haml
%h2.text-center
  - if @result[:status]
    = "找回密码邮件发送成功，请登录邮箱#{@result[:message]}进行密码找回。"
  - else
    = "找回密码邮件发送失败"

app/views/users/login.html.haml
%section.content
  .form-unit
    = link_to root_path, class: 'brand' do
      %h1= blog_title
    %h3 用户登录
    - errors = @user ? @user.errors.full_messages : []
    - if errors.any?
      .alert.alert-danger
        %a.close{"data-dismiss"=>"alert"} &times;
        %span
          = errors.first
    - if flash[:success].present?
      .alert.alert-success
        %a.close{"data-dismiss"=>"success"} &times;
        %span
          = flash[:success]
    - elsif flash[:error].present?
      .alert.alert-danger
        %a.close{"data-dismiss"=>"alert"} &times;
        %span= raw flash[:error]
    = form_for :user, url: login_confirm_users_path(from: params[:from].present? ? params[:from] : ''), role: 'form' do |f|
      .form-field.form-group
        = f.text_field :username, placeholder: '用户名', class: 'form-control username', required: true
      .form-field.form-group
        = f.password_field :password, placeholder: '密码', class: 'form-control password', required: true
      = submit_tag '登录', class: 'btn btn-primary btn-lg'
      .action-wrapper
        = link_to '没有账号？', register_path
        = link_to '忘记密码？', forget_password_users_path

app/views/users/register.html.haml
%section.content
  .form-unit
    = link_to root_path, class: 'brand' do
      %h1= blog_title
    %h3 注册账号
    - errors = @user.errors.full_messages
    - if errors.any?
      .alert.alert-danger
        %a.close{"data-dismiss"=>"alert"} &times;
        %span
          = errors.first
    = render partial: 'form', locals: {action: 'register'}

app/views/users/send_active_mail.html.haml
%h2.text-center
  - if @result[:status]
    = "激活邮件发送成功，请登录邮箱#{@result[:message]}进行激活。"
  - else
    = "激活邮件发送失败，#{link_to '点此', send_active_mail_users_path}重新发送"